export const currencies = [
  { code: "USD", symbol: "$", name: "US Dollar", rate: 1 },
  { code: "EUR", symbol: "€", name: "Euro", rate: 0.85 },
  { code: "GBP", symbol: "£", name: "British Pound", rate: 0.73 },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar", rate: 1.25 },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira", rate: 750 },
  { code: "ZAR", symbol: "R", name: "South African Rand", rate: 18.5 },
  { code: "KES", symbol: "KSh", name: "Kenyan Shilling", rate: 110 },
  { code: "GHS", symbol: "₵", name: "Ghanaian Cedi", rate: 12 },
  { code: "EGP", symbol: "£E", name: "Egyptian Pound", rate: 31 },
  { code: "MAD", symbol: "DH", name: "Moroccan Dirham", rate: 10 },
  { code: "JPY", symbol: "¥", name: "Japanese Yen", rate: 110 },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan", rate: 6.5 },
  { code: "INR", symbol: "₹", name: "Indian Rupee", rate: 83 },
  { code: "AUD", symbol: "A$", name: "Australian Dollar", rate: 1.35 },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc", rate: 0.92 },
];

export const timezones = [
  { value: "Africa/Lagos", label: "West Africa Time (WAT)" },
  { value: "Africa/Cairo", label: "Egypt Standard Time" },
  { value: "Africa/Johannesburg", label: "South Africa Standard Time" },
  { value: "Africa/Nairobi", label: "East Africa Time" },
  { value: "Africa/Casablanca", label: "Morocco Standard Time" },
  { value: "America/New_York", label: "Eastern Time (ET)" },
  { value: "America/Chicago", label: "Central Time (CT)" },
  { value: "America/Denver", label: "Mountain Time (MT)" },
  { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
  { value: "America/Toronto", label: "Eastern Time - Toronto" },
  { value: "Europe/London", label: "Greenwich Mean Time (GMT)" },
  { value: "Europe/Paris", label: "Central European Time" },
  { value: "Europe/Berlin", label: "Central European Time - Berlin" },
  { value: "Europe/Rome", label: "Central European Time - Rome" },
  { value: "Asia/Tokyo", label: "Japan Standard Time" },
  { value: "Asia/Shanghai", label: "China Standard Time" },
  { value: "Asia/Kolkata", label: "India Standard Time" },
  { value: "Asia/Dubai", label: "Gulf Standard Time" },
  { value: "Australia/Sydney", label: "Australian Eastern Time" },
  { value: "Pacific/Auckland", label: "New Zealand Standard Time" },
];
